apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-operator
  namespace: elastic-operator
data:
  eck.yaml: |-
    log-verbosity: 0
    metrics-port: 6060
    container-registry: docker.elastic.co
