apiVersion: batch/v1
kind: Job
metadata:
  name: filebeat-setup-simple
spec:
  template:
    spec:
      containers:
      - name: filebeat-setup
        image: docker.elastic.co/beats/filebeat:7.10.1
        args: [
          "setup",
          "--dashboards",
          "--pipelines",
          "--index-management",
          "--template",
          "--modules", "system,nginx",
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-simple-es-elastic-user
              key: elastic
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: filebeat-config
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    output.elasticsearch:
      hosts: ['https://elasticsearch-simple-es-http.default.svc:9200']
      username: elastic
      password: ${ELASTICSEARCH_PASSWORD}
      ssl.verification_mode: none
    setup:
      kibana:
        host: 'https://kibana-simple-kb-http.default.svc:5601'
        username: elastic
        password: ${ELASTICSEARCH_PASSWORD}
        ssl.verification_mode: none
      template.type: index
      # template.type: component