apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: toto
spec:
  version: 7.17.5
  nodeSets:
  - name: hot
    count: 2
    config:  # specific elasticsearch config
      node.roles: 
        - master
        - ingest
        - ml
        - transform
        - data_hot
        - data_content
        - remote_cluster_client
      node.attr.temp: hot
    config: &common-elastisearch-config #common elasticsearch config
      xpack.ml.enabled: true
      node.store.allow_mmap: false
      xpack.security.enabled: true
      xpack.monitoring.collection.enabled: true
      xpack.monitoring.elasticsearch.collection.enabled: false
      s3.client.my-minio.endpoint: minio-service.default.svc:9000
      s3.client.my-minio.protocol: http 
      s3.client.my-minio.path_style_access: true
    podTemplate:
      metadata:
        labels:
          scrape: es
        annotations:
          co.elastic.logs/enabled: "true"
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            /usr/share/elasticsearch/bin/elasticsearch-plugin list | grep repository-s3
            [[ $? -ne 0 ]] && /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch repository-s3 || true
        containers:
        - name: elasticsearch
          env: 
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          resources:
            requests:
              memory: 2Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 2
        nodeSelector: 
          temp: hot
        # affinity:
        #   nodeAffinity:
        #     requiredDuringSchedulingIgnoredDuringExecution:
        #       nodeSelectorTerms:
        #       - matchExpressions:
        #         - key: temp
        #           operator: In
        #           values:
        #           - hot
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi

