apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.15.1
  count: 2
  elasticsearchRef:
    name: elasticsearch
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: monitoring-cluster
    logs:
      elasticsearchRefs:
      - name: monitoring-cluster
  config:
    # https://www.elastic.co/guide/en/kibana/current/monitoring-metricbeat.html
    elasticsearch.customHeaders:
      x-opaque-id: kibana
  podTemplate:
    metadata:
      labels:
        scrape: kb
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 1Gi
            cpu: 2

