# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: localhost:5000/kindest/node:v1.30.0
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "beta.kubernetes.io/instance-type=highstorage,topology.kubernetes.io/zone=az1"
  image: localhost:5000/kindest/node:v1.30.0
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "beta.kubernetes.io/instance-type=highstorage,topology.kubernetes.io/zone=az2"
  image: localhost:5000/kindest/node:v1.30.0
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "beta.kubernetes.io/instance-type=highio,topology.kubernetes.io/zone=az1"
  image: localhost:5000/kindest/node:v1.30.0
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "beta.kubernetes.io/instance-type=highio,topology.kubernetes.io/zone=az2"
  image: localhost:5000/kindest/node:v1.30.0
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "beta.kubernetes.io/instance-type=highio,topology.kubernetes.io/zone=az1"
  image: localhost:5000/kindest/node:v1.30.0
