#based on and extend https://github.com/elastic/cloud-on-k8s/blob/master/config/recipes/beats/stack_monitoring.yaml
---
# metricbeat resources
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat-stack-monitoring
spec:
  type: metricbeat
  version: 7.12.1
  elasticsearchRef:
    name: elasticsearch
  config:
    http:
      enabled: true
      host: 0.0.0.0
      port: 5067
    metricbeat:
      autodiscover:
        providers:
          - type: kubernetes
            scope: cluster
            hints.enabled: true
            templates:
              - condition:
                  contains:
                    kubernetes.labels.scrape: es
                config:
                  - module: elasticsearch
                    metricsets:
                      - ccr
                      - cluster_stats
                      - enrich
                      - index
                      - index_recovery
                      - index_summary
                      - ml_job
                      - node_stats
                      - shard
                    period: 10s
                    # TODO switch to using named ports in 7.9.0 when https://github.com/elastic/beats/pull/19398 is added
                    hosts: "https://${data.host}:9200"
                    username: ${MONITORED_ES_USERNAME}
                    password: ${MONITORED_ES_PASSWORD}
                    # WARNING: disables TLS as the default certificate is not valid for the pod FQDN
                    # TODO: switch this to "certificate" when available: https://github.com/elastic/beats/issues/8164
                    ssl.verification_mode: "none"
                    xpack.enabled: true
              - condition.or:
                  - contains.kubernetes.labels.scrape: fb
                  - contains.kubernetes.labels.scrape: hb
                config:
                  - module: beat
                    period: 10s
                    hosts: "http://${data.host}:5066"
                    # username: ${MONITORED_ES_USERNAME}
                    # password: ${MONITORED_ES_PASSWORD}
                    # # WARNING: disables TLS as the default certificate is not valid for the pod FQDN
                    # # TODO: switch this to "certificate" when available: https://github.com/elastic/beats/issues/8164
                    # ssl.verification_mode: "none"
                    xpack.enabled: true
              - condition.contains.kubernetes.labels.scrape: mb
                config:
                  - module: beat
                    period: 10s
                    hosts: "http://${data.host}:5067"

                    xpack.enabled: true
              - condition:
                  contains:
                    kubernetes.labels.scrape: kb
                config:
                  - module: kibana
                    metricsets:
                      - stats
                      - status
                    period: 10s
                    hosts: "https://${data.host}:${data.port}"
                    username: ${MONITORED_ES_USERNAME}
                    password: ${MONITORED_ES_PASSWORD}
                    # WARNING: disables TLS as the default certificate is not valid for the pod FQDN
                    # TODO: switch this to "certificate" when available: https://github.com/elastic/beats/issues/8164
                    ssl.verification_mode: "none"
                    xpack.enabled: true
    processors:
    - add_cloud_metadata: {}
    logging.json: true
  deployment:
    podTemplate:
      metadata:
        labels:
          scrape: mb
        annotations:
          co.elastic.logs/enabled: "true"
          co.elastic.logs/processors.1.add_fields.fields.dataset: "metricbeat.log"
          co.elastic.logs/processors.1.add_fields.target: "event"
          co.elastic.logs/json.keys_under_root: "true"
          co.elastic.logs/processors.2.drop_event.when.equals.logger: "monitoring"
      spec:
        serviceAccountName: metricbeat-stack-monitoring
        automountServiceAccountToken: true
        # required to read /etc/beat.yml
        securityContext:
          runAsUser: 0
        containers:
        - name: metricbeat
          env:
          - name: MONITORED_ES_USERNAME
            value: elastic
          - name: MONITORED_ES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: elastic
                name: elasticsearch-es-elastic-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat-stack-monitoring
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat-stack-monitoring
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat-stack-monitoring
subjects:
- kind: ServiceAccount
  name: metricbeat-stack-monitoring
  namespace: default
roleRef:
  kind: ClusterRole
  name: metricbeat-stack-monitoring
  apiGroup: rbac.authorization.k8s.io
---
# filebeat resources
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-stack-monitoring
spec:
  type: filebeat
  version: 7.12.1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    http:
      enabled: true
      host: 0.0.0.0
    filebeat:
      autodiscover:
        providers:
        - type: kubernetes
          host: ${HOSTNAME}
          hints:
            enabled: true
            default_config:
              enabled: false
              type: container
              paths:
                - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    logging.json: true
  daemonSet:
    podTemplate:
      metadata:
        labels:
          scrape: fb
        annotations:
          co.elastic.logs/enabled: "true"
          co.elastic.logs/processors.1.add_fields.fields.dataset: "filebeat.log"
          co.elastic.logs/processors.1.add_fields.target: "event"
          co.elastic.logs/json.keys_under_root: "true"
          co.elastic.logs/processors.2.drop_event.when.equals.logger: "monitoring"
      spec:
        serviceAccountName: filebeat-stack-monitoring
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        containers:
        - name: filebeat
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-stack-monitoring
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-stack-monitoring
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-stack-monitoring
subjects:
- kind: ServiceAccount
  name: filebeat-stack-monitoring
  namespace: default
roleRef:
  kind: ClusterRole
  name: filebeat-stack-monitoring
  apiGroup: rbac.authorization.k8s.io
---
