apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rally-benchmarks-volume
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
